[theme]
base = "dark"
primaryColor = "#f59e0b"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
